FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY ./src ./src
COPY ./models ./models   

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "src.streaming.fastapi_tweet:app", "--host", "0.0.0.0", "--port", "8000"]
